### ISSUE TITLE
Simple check

### ISSUE THREAD

**Issue by cornae** [euphorie/osha.oira#124]
Solves the checking of machines and other resources that are well documented and understood. 

Idea for solution: 

An extra content type that comprises the following page modules: 
- A simple extensible checklist (new page module type)
- Page module 'resources' (existing)

This content type can be used in any risk assessment.

**Comment by pysailor** [comment]
Closing, was in wrong repo.
See https://github.com/syslabcom/oira.prototype/issues/210
