### ISSUE TITLE
Advanced check

### ISSUE THREAD

**Issue by cornae** [euphorie/osha.oira#125]
Advanced check facilitates checking objects/environments for which nog proper documentation is available. 

## Possible solutions

- Extra fields are required on the tool config level OR tied to a new tooltype. These fields are currently fixed to the tool type.
- The same content type as for simple check could apply.
- For the more complex situation (page 15 of Ines' PP) the current risk content type seems sufficient…
- Training module needs to support existing training material. (Word? PowerPoint? PDF?)

**Comment by pysailor** [comment]
Closing, was wrong repo.
see https://github.com/syslabcom/oira.prototype/issues/211
