### ISSUE TITLE
Action plan improvement

### ISSUE THREAD

**Issue by cornae** [euphorie/osha.oira#13]
For Action plan, I would like to make one improvement to the collapsible and that is to give them accordion behaviour. Patterns doesn't have a dedicated accordion Pattern, but what if we added the properties `trigger-close:` and `trigger-open:` to the stack. 

Additional separate selectors for close and open buttons is a feature that I have wished for in more occasions, but could work around so far. In this case I would make the Clone button also the trigger button to close all open collapsible. Except the new clone which is made directly after so will hopefully stay open.

@jcbrand, What do you think?

**Comment by jcbrand** [comment]
It's a bit unclear to me how accordion behavior will come from this. If you have ``trigger-open`` and ``trigger-close`` buttons, wouldn't they just be applying to the specific ``pat-collapsible`` element?

You have multiple ``pat-collapsible`` elements and you want all to close and a single one to open. I don't see how these individual arguments on each element achieves that.

**Comment by cornae** [comment]
It depends I guess what's executed earlier. Add clone or close collapsible. If add clone happens after close collapsible and the clone template has closed on it then i guess the clone would stay open.

**Comment by jcbrand** [comment]
Well, you said this:

> In this case I would make the Clone button also the trigger button to close all open collapsible

but wouldn't ``trigger-close`` logically only be limited to one particular ``pat-collapsible`` element? So ``trigger-close`` won't close all open collapsibles (unless we add that as a feature somehow).

**Comment by cornae** [comment]
I wanted to user a CSS selector with a class like you currently already can do with the trigger property. Like that you can already toggle mulltiple collapsibles at once. Or do I misunderstand your question?

**Comment by jcbrand** [comment]
Ok. Sounds good.

I'm just wondering, when you want to specifically close only the current ``pat-collabsiple`` element (via a button inside that element) what kind of selector would you then use? I'm not aware of a selector with which you can say, only inside this pattern's element.

**Comment by cornae** [comment]
Only if you have an ID to work with on the collapsible instance. Because we work the selector from the html element and not from the container element of the pattern itself.

**Comment by jcbrand** [comment]
Ok, if you're happy with it like that then I'll add the ``.trigger-open`` and ``.trigger-close`` options.

**Comment by cornae** [comment]
Cool. And you also think that it will work the way I imagine in combination with clone in terms of in which order things will happen?

**Comment by jcbrand** [comment]
Yeah, there might be some timing issues. I'll have to take a closer look. If necessary we could add a 50ms delay before the element is cloned.

**Comment by jcbrand** [comment]
Redmine ticket: https://projects.syslab.com/issues/11521

**Comment by jcbrand** [comment]
@cornae I've updated the bundle in OiRA with a new version of pat-collapsible which adds the options ``close-trigger`` and ``open-trigger``.

I could not name them ``trigger-close`` or ``trigger-open`` because of a technical issue with the patterns argument parser for which I could not find a viable workaround.

Can you take it for a spin?

**Comment by pysailor** [comment]
@cornae I updated _layouts/action.html accordingly. Now, when a new measure gets added, the other existing ones close.

**Comment by cornae** [comment]
trigger-open/trigger-close fine.

Works like a charm. Brilliant!
