### ISSUE TITLE
Screen Identification (risk)

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#15]
Basically done (text and images not yet shown), just for completeness' sake 
Example: https://client.oiratest.syslab.com/eu/eu-private-security/private-security-eu/identification/2/1/1/2 (need to start a session first)
A risk has a title (the "positive statement"), a description (rich-text) and optionally Legal and Policy references. A risk can have 1 main image and up to 3 secondary images. The risk page also includes a comment box.
Already done: the merging in of the evaluation phase into the identification screen

![screen shot 2015-03-22 at 10 59 12](https://cloud.githubusercontent.com/assets/642660/6768887/c35732d8-d082-11e4-9b04-505b52fd7a03.png)

**Comment by cornae** [comment]
Is it correct that in the risk .md files the page content is each time the same the description parameter value (which is escaped HTML)?

**Comment by pysailor** [comment]
Cornelis G. A. Kolbach wrote on 22/03/15 23:34:
>
> Is it correct that in the risk .md files the page content is each time
> the same the description parameter value (which is escaped HTML)?
>

Yes, that's right. `description` holds the description content (escaped
HTML), and `legal_references` (also escaped HTML) the Legal and policy
references.

**Comment by cornae** [comment]
Alright so if i just use the page content it should be fine right? I can't use the escaped HTML

**Comment by pysailor** [comment]
Ah, now I understand the question.
So it's a flaw of our export script. But we can easily change it so that the escaped HTML gets turned into normal HTML.
