### ISSUE TITLE
Screen Action Plan

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#16]
Already in progress, just for completeness' sake.
A risk screen in an action plan has:
* title (the "negative statement")
* description, including images, like in the identification screen
* A selector for setting the priority
* A form for defining a measure. The form can be added multiple times for separate measures
* A selector for pre-filling the measure fields with one of the standard solutions
* A comment box (same as on the identification screen)
* Legal and Policy references (contents hidden by default)

![screen shot 2015-03-22 at 11 07 57](https://cloud.githubusercontent.com/assets/642660/6768912/ef8717dc-d083-11e4-8bf6-687579210407.png)
![screen shot 2015-03-22 at 11 08 29](https://cloud.githubusercontent.com/assets/642660/6768913/f2bffaf4-d083-11e4-8873-c1ba64dc4cc3.png)

**Comment by cornae** [comment]
There's only one .js ticket left for action plan, that I have to write a ticket for.
