### ISSUE TITLE
User can define custom risks

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#18]
New development. In the app, a user should be able to define their own custom risks in addition to those that were set down by the tool creator. This improvement comes from a request expressed by several OiRA partners, so that an organisation can add risks that are present in their specific situation to OiRA - that means those custom risks will appear also in the action plan.

In the main nav, below all the modules, there should be a separate entry "Other risks", example:
![other-risks](https://cloud.githubusercontent.com/assets/642660/7050348/1d628704-de21-11e4-8ce2-ac500ec708f9.png)

This page will 1) list all custom risks that are already defined and 2) offer the possibility to add new risks. Example:
![other-risks-cover](https://cloud.githubusercontent.com/assets/642660/7050371/45a89d8e-de21-11e4-9300-9ebc9c7f21c4.png)

"Add custom risk" would open a simple form for adding the risk description (e.g. "Fire extinguishers are not clearly marked"), adding a comment and setting the priority. Example:
![other-risks-add-new](https://cloud.githubusercontent.com/assets/642660/7050486/f5bdf14c-de21-11e4-8901-e4706b65d834.png)

"Edit risks" with existing custom risks would offer the possibility to change texts or delete a risk. Example
![other-risks-existing](https://cloud.githubusercontent.com/assets/642660/7050510/1c2bac20-de22-11e4-993b-5c8a4e653be0.png)

**Comment by pysailor** [comment]
@cornae We still need the enhancement of pat-clone, to allow deleting the first element, right?

**Comment by cornae** [comment]
Ah yes, we need a ticket for that. I'm also interested in @jcbrand's opinion if I'm not asking for something weird or if I could technically solve it in another way, keep the same UID.
