### ISSUE TITLE
Guest User

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#19]
Partly handled already in #4, but here for completeness's sake.

Users who don't want to register and log in should be able to start any OiRA tool session as "guest user". While using the application as a guest user, there is always the possibility to register as a new user or logging in with an existing account. In both cases the already entered data is kept (<-- technical note, already handled in the backend).

Limitation of the guest user: Reports cannot be created and downloaded. That means the "report" screen for guest users (#10) will be different (i.e. minus the download possibilities, but showing a text plus image instead).

During a guest user session, every screen shows a warning that all data entered will be lost unless the user registers.
Example (and I mean example, not design requirement ;-) ):
![screen shot 2015-04-08 at 20 09 23](https://cloud.githubusercontent.com/assets/642660/7052031/503470f6-de2c-11e4-8134-f2323a41a796.png)

Warning in plain text:
You are currently evaluating OiRA as a guest user. You will not be able to save your progress or download any reports. To save your work, please sign in or register by clicking the "sign in" link at the top right of the page.

**Comment by cornae** [comment]
I used a very short text that fits in the top bar. I'll close the ticket for now. Should we want the long text, then a [ ? ] there could be useful that show this longer text.

**Comment by pysailor** [comment]
@cornae Thanks. I made the text slightly longer, since I think it was a bit too cryptic for non-technical users. How limited are we with the space? Is that text now too long already (also considering translations)?

But the actually desired text will of course not fit in like that anyways. Can you please add the [ ? ] solution? I think it's great to see the "Register" call to actions immediately. So the longer explanation from the original ticket description could go into the info bubble.

**Comment by cornae** [comment]
Any character you've added will increase the risk it no longer fits on screens of pocket devices. That's why I was search for the shortest possible text. There is an alternate scenario which is that I will put a bar above the toolbar (Only in this warning mode), pushing the toolbar down. More expensive solution though. 

Yes, I can add the [ ? ]

**Comment by pysailor** [comment]
Cornelis G. A. Kolbach wrote on 23/04/15 10:17:
> Any character you've added will increase the risk it no longer fits on
> screens of pocket devices. That's why I was search for the shortest
> possible text. There is an alternate scenario which is that I will put
> a bar above the toolbar (Only in this warning mode), pushing the
> toolbar down. More expensive solution though.
Ok, please go for it. I'm worried that the client will want longer
texts, and also about the translations.

>
> Yes, I can add the [ ? ]
Great.
