### ISSUE TITLE
Screen "Password reminder"

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#24]
https://client.oiraproject.eu/eu/@@reminder

Linked from Login "I forgot my password"

![screen shot 2015-04-25 at 15 47 39](https://cloud.githubusercontent.com/assets/642660/7333125/92a12a68-eb62-11e4-947d-b0e30c630b3d.png)

**Comment by cornae** [comment]
I've tried call for the forgot password dialogue in an elegant manner by adding `class="close-panel pat-modal"` to the linke.

The link is present on the login panel which yo get when you click on the button 'login' on the toolbar.

The closes, however a new modal doesn't open. We've discussed the probability of one modal calling of the next in the past but I think we never came to a resolution as I always try to avoid this interaction pattern. In this case however I don't see a better option. 

I tried avoid the issue by simply replacing the content of the modal only, with injection. This works nicely, except that pat-modal doesn't recalculate the height of the modal, after an injection takes place inside the modal. Isn't the latter probably the more easy thing to fix to solve this problem?

**Comment by cornae** [comment]
@pysailor, Can I get some follow up on my comment of a week ago? I can't continue with it.

**Comment by pysailor** [comment]
@cornae Yes, it's good the way it is. I.e. we need to fix the resizing of modals after injections.
For creating a screen-shot, we can just call forgot-password.html directly, right?

**Comment by cornae** [comment]
Yes
