### ISSUE TITLE
Concept / styling for notifications

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#25]
There are some instances where feedback is given to the user after a successful action.

Example: If you enter your email address on https://client.oiraproject.eu/eu/@@reminder (you can use thomas@no-support.com for testing), the next screen shows feedback:

![screen shot 2015-04-25 at 15 59 14](https://cloud.githubusercontent.com/assets/642660/7333173/a1d42a2e-eb64-11e4-9311-c48a11cc2e7f.png)

In the new proto, this might be a case for pat-notification. It seems functional, but you might want to check if the styling needs adjustment:

![screen shot 2015-04-25 at 16 00 18](https://cloud.githubusercontent.com/assets/642660/7333176/ba0034ee-eb64-11e4-84b5-61115a729315.png)

**Comment by cornae** [comment]
pat-notification seems a fine choice to me. CSS needs some love still.
