### ISSUE TITLE
Adding several info texts to the "Test session" screen

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#27]
I debated a long time whether I should paste here the  screens we got  regarding the "Start new test session" function. But they do illustrate the point....
Screens first, then some explanations:
![pwc-test-session-1](https://cloud.githubusercontent.com/assets/642660/7333716/ca49d85e-eb79-11e4-8a9e-cb03631c3779.png)
![pwc-test-session-2](https://cloud.githubusercontent.com/assets/642660/7333717/ce777cce-eb79-11e4-9ae9-ed1906263bbf.png)

This is supposed to mean that on the panel to start a new test session, there's some text the explains the benefits (left on both screen-shots). Then there's some more text, hidden in a modal, that explains the limitations (top right). And finally, another modal that explains why it makes sense to register, including a link to register.(top right).

Without commenting further on the quality of this design... We do have the requirement to make available the 3 different texts (benefits, limitations, why register) and the call to action ("register").

**Comment by pysailor** [comment]
@cornae 
Ok, I made quite an ugly suggestion in f45230d - probably breaking several design principles. Please consider this as a suggestion from a mere developer ;) And feel free to go into a completely different direction.
One thing that came to my mind: since we need to accommodate so much (rich!) text, might it make more sense to not use a panel, but a full page like for registration.html? 
=> Let's discuss

**Comment by cornae** [comment]
I agree that a full page would make a lot of sense.
