### ISSUE TITLE
Allow for variying navigation depths of risks

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#28]
Currently the proto assumes the following structure regarding modules and risks

```
   Level 1: module
        Level 2: sub-module
            Level 3: risk
```

![screen shot 2015-04-28 at 15 27 55](https://cloud.githubusercontent.com/assets/642660/7370558/3614b868-edbb-11e4-84b2-48f15e8ec48a.png)

In the real world, there are 2 other possible scenarios:

1) Risks directly in a module
```
    Level 1: module
       Level 2: risk
```
![screen shot 2015-04-28 at 15 23 03](https://cloud.githubusercontent.com/assets/642660/7370459/92ed706c-edba-11e4-8250-629f1bebea94.png)

2) Module is a profile question, so that there is an extra level for the location in the navigation
```
    Level 1: module (profile question)
        Level 2: Location name
            Level 3: submodule
                Level 4: risk
```
![screen shot 2015-04-28 at 15 23 22](https://cloud.githubusercontent.com/assets/642660/7370489/ccbb5dae-edba-11e4-8cdf-829b2f8abaaf.png)

The markup / CSS needs to be able to handle those possibilities

**Comment by pysailor** [comment]
@cornae  in 93ef3b5 and 2f9dd3e I updated shell.hmtl to handle the case of a) no submodules and b) locations in profile questions.
I also updated the exported tool files so that we now have:

1. **Commercial manned guarding**: Module with submodules (same as before)
2. **Mobile partrolling / intervention after alarm**: Profile question with 2 locations and submodules
3. **OSH management**: Module without submodules

For 2. and 3. I tried to replicate your markup of the hard-coded examples exactly. 
Note: for 3. (Module with risks directly in them), the risks are not connected via the metro-line - intentional?

Can you please check if all is OK?

**Comment by cornae** [comment]
With the new separation headers (Without numbers ;)) I think this is solved now.
