### ISSUE TITLE
Pat-clone

### ISSUE THREAD

**Issue by cornae** [euphorie/osha.oira#3]
For the action plan we used to have a dedicated script that cloned the tabs. For the new situation the interaction pattern and markup have changed and therefor new JavaScript is required. I suggest to write this JavaScript as a Pattern that is generic and can be added to Patternslib so that we can use it for other projects too. Draft documentation may be found on https://github.com/Patternslib/Patterns-site/blob/gh-pages/_posts/2014-08-27-clone.md

**Comment by cornae** [comment]
@pysailor, If you agree with this, could you then distribute this ticket further? Then I can finish the action plan.

**Comment by pysailor** [comment]
@cornae Thanks, I made an internal ticket for us out of this.

**Comment by jcbrand** [comment]
@cornae I'm finished with pat-clone. What needs to be done to make it available for you in your osha.oira proto?

**Comment by cornae** [comment]
Great, I don’t know, I guess you have to do some magic so that I can pull it in OiRA with make designer happy?

**Comment by jcbrand** [comment]
@cornae I've added a new files to the bundles directory in the oira proto. So you should be able to use *pat-clone* in the proto.

**Comment by cornae** [comment]
It works! Very happy.

So far found two unforeseen things. 

1. The cloned item has a Pattern on it itself. In this case pat-collapsible. Pat-collapsible is not triggered on the clone. 
2. The DOM version of the element is cloned and not the HTML source version, so it’s cloned with DOM transformation and all. I didn’t think about this at frist that this would happen. 

I thought about solving #2 by adding a hidden template, but I haven’t tried this yet. Patterns might also apply transformations to hidden stuff. 

Issue number 1 seems to be reveal a wider problem. A clone may always have other Patterns on or in it, such as toggle, switch, collapsible, inject or others. 

Any thoughts?

**Comment by jcbrand** [comment]
About #1 we need to scan again the the clone after it's been inserted.
About #2, there's a class **cant-touch-this** which prevents a node from being processed by patterns. So you can use a hidden template and put that class on it so that it doesn't get patternised.

**Comment by cornae** [comment]
#1 Sounds good then.
#2 I didn't know that! Great, all is solved then.

> I told you homeboy (You can't touch this)
> Yeah, that's how we're living and you know (You can't touch this)
> Look in my eyes, man (You can't touch this)
> Yo, let me bust the funky lyrics (You can't touch this)

**Comment by jcbrand** [comment]
Is there some markup somewhere which I can use to test # 1?

**Comment by cornae** [comment]
No, my intention was to add a template to action.html layout. But feel free
to add something in it for testing.

Op donderdag 19 maart 2015 heeft JC Brand <notifications@github.com> het
volgende geschreven:

**Comment by cornae** [comment]
I can do it now if you like unless you’re already doing it.

**Comment by jcbrand** [comment]
@cornae: please do, I'm busy with something else at the moment.

**Comment by cornae** [comment]
Done

**Comment by jcbrand** [comment]
@cornae: I've fixed # 1 in pat-clone and updated the bundles in osha.oira and ploneintranet.

I see in action.html that you used **dont_touch_this** instead of **cant_touch_this**.
In any case, I'm not sure anymore that this is a proper solution. The reason being that the patterns inside the clone will *never* be processed, even after cloning.

So your idea of just using a hidden template is the best solution I think.

**Comment by jcbrand** [comment]
@cornae you somewhere asked about ``# {1}`` not being updated in a clone (when it's a template). It should be always updated but there was a bug where more deeply nested elements weren't updated. That's now been fixed as well and already available to you.

**Comment by cornae** [comment]
Yes that was in The oira group on Syslab Slack. :)  thanks!

Op vrijdag 20 maart 2015 heeft JC Brand <notifications@github.com> het
volgende geschreven:

**Comment by cornae** [comment]
It is updated but **only** when in a template. It's not updated when outside a template. I have this problem on 'profiling.html' in the OiRA prototype. 

![image](https://cloud.githubusercontent.com/assets/738601/6762438/9183870c-cf60-11e4-8fe8-3209ca75b2a4.png)

**Comment by jcbrand** [comment]
Currently, the way the code works is that once a clone is created, the numbers gets updated.
In your example above, the element is not cloned, it is only shown via pat-depends.
The numbers will only be updated when you click **Add another item** because that will create a clone.[1]

If from the beginning the code changes ``#{1}`` with a number, then whenever a clone is created from that element, we don't have the original ``#{1}`` anymore and we won't know what should be replaced with a new number. Therefore I think the ``#{1}`` replacement doesn't make sense outside of templates.

Does this make sense?

*Footnotes:*
[1] In your example, the number doesn't get updated when you click **Add another item** because the attribute is *placeholder* and in the docs of pat-clone you only mentioned *text* as well as the *name* and *value* attributes. I'll update pat-clone to also update *placeholder*.

**Comment by jcbrand** [comment]
I've updated pat-clone to now also change the *placeholder* attr.

**Comment by cornae** [comment]
I can follow that and I agree. I guess I'll have to rewrite this to make it work with a template.

**Comment by cornae** [comment]
Alright. Now I see what you meant with updating the placeholder attributes. It looks like the script looks for any kind of number in the placeholder attribute value, but I intended it to be limited to the #{1} kind of strings and replace that whole thing. I understand we need a template for that, so I'll update the page accordingly. But I think the code that updates any number there should be taken out. It can have really weird side effects. 

For the action plan I use injection targets with a #{1} syntax in there. It looks like those are not transformed into numbers before pat-inject is triggered. Would it be possible and a good idea to let the script just scan for anything #{some number} throughout the template and just specifically in content or attribute values?

**Comment by jcbrand** [comment]
>  It looks like the script looks for any kind of number in the placeholder attribute value, but I intended it to be limited to the #{1} kind of strings and replace that whole thing.

Oops! That was a bug. Fixed now.

> For the action plan I use injection targets with a #{1} syntax in there. It looks like those are not transformed into numbers before pat-inject is triggered. Would it be possible and a good idea to let the script just scan for anything #{some number} throughout the template and just specifically in content or attribute values?

I'll have to think about it a bit more and how we could do that. How high priority is this? I've moved on now to StarAlliance stuff again and am a bit overloaded ATM.

**Comment by cornae** [comment]
It's not up to me to prioritise between oira and star. This addition is
needed though to finish the action plan.

Op donderdag 26 maart 2015 heeft JC Brand <notifications@github.com> het
volgende geschreven:

**Comment by jcbrand** [comment]
Yeah, *priority* is not the right word. I just wanted to know whether this is a blocker or whether it can be done later.

**Comment by cornae** [comment]
We couldn't deliver without it, but I could not click on any second and on standard solutions link during the demo's ;).

**Comment by jcbrand** [comment]
I've now updated pat-clone now to increment **#{1}** on all attributes of DOM nodes and text nodes.

As far as I'm aware, there aren't any more outstanding requirements for this issue.

**Comment by cornae** [comment]
Works very well. Super!
