### ISSUE TITLE
Guest user session: warning when closing browser

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#30]
When in a guest user session and the user wants to close the current browser window, issue a warning (pop-up):

![guest-user-warning](https://cloud.githubusercontent.com/assets/642660/7371837/989d8214-edc3-11e4-8731-49b8b8b0ba38.png)

Actually, we might not need this in proto, only in the live version. But we need to create a screen-shot for it

**Comment by cornae** [comment]
@pysailor, What will happen with this ticket now we decided to bounce this?

**Comment by pysailor** [comment]
I'll take it

**Comment by pysailor** [comment]
wontfix
