### ISSUE TITLE
Screen login

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#4]
https://client.oiratest.syslab.com/eu/@@login
Apart from the actual login form, it contains 3 links to other actions: 
* password reminder
* registration
* use tool as guest user (new feature)

For the last two functions, we need the possibility to show more information about them. These are the texts we got from pwc:

**Guest user**
  Benefits:
    * Discover how easy it is to create a risk assessment with OiRA.
    * Identify potential risks in the business and the measures to reduce them.
    * Use it for vocational training
 
  Limitations:
    * **Important**: As a guest user you cannot save your work. All the progress will be lost unless you register.
    * You will not be able to download or print reports.
    * While you're using OiRA as a guest user, you will have the possibility to register at any time by clicking the "Sign in" button.

**Why register?**
You can register in one single step just by entering a valid email address.

Main benefits of having an account:
* It's free
* You can save your work online
* You can download a full report and action plan

![screen shot 2015-03-18 at 19 24 58](https://cloud.githubusercontent.com/assets/642660/6716272/880468ee-cda4-11e4-8beb-6177df7cddea.png)

**Comment by cornae** [comment]
I'm experimenting with having a separate button for test session and a separate screen for al the USPs if you think that's fine.
