### ISSUE TITLE
Measure pre-fills not displayed correctly

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#42]
Hi,

we noticed that on the action plan, the "standard measures" pre-fill does not get populated correctly any more. 

I've hunted down that this regression has appeared with this commit: 300740e

![screen shot 2015-05-28 at 14 18 04](https://cloud.githubusercontent.com/assets/642660/7859840/67f591f4-0544-11e5-86ac-d30de598ca54.png)

**Comment by cornae** [comment]
Hmm an issues of different versions of pat-tooltip lingering around across projects that I tried to manually bring in sync. I’ll have a look.
