### ISSUE TITLE
Improve pat-clone

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#43]
Follow-up of #3 

Currently, pat-clone will increment `#{1}` inside attributes (hard-coded). However, this is not flexible enough for the real-world usage.

Image you are re-visiting an action plan screen in which you have previously entered measures already. Now you need to come back and add a new measure. This new measure should of course not be "measure 2" but (number of existing measures + 1).

Therefore, pat clone needs to handle this as a regular expression. Following https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions I made this little example:

    var myRe = /.*(#\{\d*\}).*/g;
    var myArray = myRe.exec('Measure #{5}')
        Array [ "Measure #{5}", "#{5}" ]
    "Measure #{5}".replace(myArray[myArray.length-1], '13')
        "Measure 13"

which _might_ do the trick already

**Comment by pysailor** [comment]
This might have just become obsolete with #44

**Comment by jcbrand** [comment]
Closed in favour of #44
