### ISSUE TITLE
Alternative solution for truncating text in identification and action plan

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#45]
Hi @cornae 

I don't see a technical solution for implementing text cropping on a risk (identification and action plan), as is is present in the prototype.
The reason is, of course, that the text to be cropped contains HTML and is not plain text.

The prototype assumes that from a given description, there will be Part 1 (with HTML markup), an ellipsis & "read more", and a Part 2, containing the rest of the text (with HTML markup).

I don't know of a reliable method for splitting text inside HTML markup in the middle.

I would propose the following alternative: for the initial part of the text (the "teaser"), we strip all HTML markup, and then apply truncation. A click on "read more" would then not show the rest of the text, but replace the teaser with the full text, which would then be rendered with HTML markup.

What do you think? Would that be a case for pat-switch?

**Comment by pysailor** [comment]
@cornae Of course, any other alternative solution you can come up for showing / hiding the description would be welcome too.

**Comment by cornae** [comment]
As discussed this afternoon :)
