### ISSUE TITLE
Scroll position issue

### ISSUE THREAD

**Issue by cornae** [euphorie/osha.oira#49]
Experiment with autoload

**Comment by cornae** [comment]
@pysailor I have an idea for the scrolling problem that is not an ugly highly specify hack for only this project. 

On https://www.syslab.com/ we use smooth-scroll.js. This was never patternised to pat-smooth-scroll but I think this is easy to do and this still had to happen. I have the need for pat-smooth-scroll often other project, including Plone Intranet. 

Now if we patternise smooth-scroll.js, I would request for a property `trigger:`, which would similar to the trigger property of pat-inject listen to the values 'click' (default) and 'auto'. And maybe also 'visible' but I don't have a usecase for it yet. 'Auto' would execute the smooth scroll script the moment the page load or an injection with the smooth scroll anchor on it takes place.

Smooth-scroll.js works at least on the viewport, but we have to make sure it also works on elements with overflow: auto like we have in applications such as OiRA and PI.

**Comment by jcbrand** [comment]
This is now fixed and exposed in the prototype on the master branch.
https://github.com/euphorie/osha.oira/commit/71fb24e2e87c6860cd2eff90c6880d652ced387b

I've created a new pattern, **pat-scroll**, see the initial docs here:
https://github.com/Patternslib/Patterns/blob/master/src/pat/scroll/documentation.md
