### ISSUE TITLE
Screen "change password"

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#50]
The challenge here is that the fields are auto-generated, i.e. everything inside the `<fieldset>` comes from the backend, and we can't influence the markup.

**Comment by cornae** [comment]
Then we have to find a way. Nutting and bolting CSS on for exceptions is the worst kind of monkey patch. Deliverance rule?

**Comment by pysailor** [comment]
Well, you worked around it in old Oira, so I'm hoping the markup is not too terrible... ;)

On the other hand, if this takes more than an hour of your time, we'll need to do it in the backend (even though it will take us more than an hour to refactor this).

**Comment by cornae** [comment]
Surely this markup lives 'somewhere' where it can be changed to match our
fully standardised form markup across all projects.

Op vrijdag 5 juni 2015 heeft Wolfgang Thomas <notifications@github.com> het
volgende geschreven:

**Comment by pysailor** [comment]
Believe me, it's very complicated. 
"z3cform"
That word causes every Plone developer to cringe in fear.

**Comment by cornae** [comment]
But it's 'just' markup ;)

Op vrijdag 5 juni 2015 heeft Wolfgang Thomas <notifications@github.com> het
volgende geschreven:

**Comment by pysailor** [comment]
LOL
Designers.... ;)

That's the whole problem of z3cform. It's so intelligent to generate the most complex forms with nesting and whathaveyounot, but it's a PITA to influence the markup.

We could rip that out and build the forms ourselves, but that means changing the handling code as well. 
If you have to perform hideous compromises in your CSS, we might need to do it. But it's not a trivial effort for us.

**Comment by cornae** [comment]
It turns out that the only issue is this `<div class=" z3cFieldContainer”>` the generator puts in there (WHY??). If you can generate it without that div, then  you don’t have to change anything else. If not, then I’ll have to split off the entire form styling which is very complex and standardised now across all projects. Also meaning OiRA won’t benefit from any additions and fixes to anything to do with forms coming from other projects :(.

**Comment by pysailor** [comment]
jaja, OK
I'll bite the bullet and dig into z3cform

**Comment by cornae** [comment]
Bon courage :)

**Comment by pysailor** [comment]
thanks ;) I already know I'll get very dirty
