### ISSUE TITLE
Revised "Status" page

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#54]
Here are the requirements for the updated "Status" screen.

1) General set-up of the page
* The heading contains the words "Status for" and the name of the tool
* For every module of the current tool, a section of the page is created (details below), with the title of the module as sub-heading for this section
* Only top-level modules are considered. That means, if a module contains sub-modules, only the overall status of the top-level module is shown on the "Status" screen.
* If the module is a profile question, it will be repeated for every location the user has entered, with the name of the location as part of that module's sub-heading

2) Status Bars
As it was already the case, a status bar should be displayed for every module.
Currently, there are 4 different colours used on the Status screen:
* Green: Risk not present in the organisation (question answered with ‘Yes’).
* Red: Risk identified in the organisation (question answered with ‘No’).
* Orange: Risk postponed (No answer given and click on ‘Save and continue’).
* Grey: Risk not answered yet.

The risks under "Red" should be split into two separate categories:
* Dark red: Risk identified in the organisation (question answered with ‘No’).
* Light red: Risk identified in the organisation (question answered with ‘No’), but at least 1 measure is present

The link on the status bar to the current module inside the Identification phase should be kept as it is.

3) Legend
Under the status bar, a legend tells the user what the different colours mean.
For every option out of the 5 possibilities, the absolute number of risks in that category is shown 

4) High priority risks
Under the legend, all present risks from that module that are high priority risks are listed, using the "negative statement"

5) Direct access to Action Plan per module
Under the high priority risks, there will be a direct link to the current module inside the action plan, as a "call to action" to do something about the risks.

6) Navigation
Since the Status page might get considerably longer that it currently is, an anchor-based secondary navigation should allow direct access to the details of each module. (Reason for using anchor navigation and not injection: the status for all modules should be present in a single screen).
For the "Private Security EU" example from the prototype, this would be:

* OSH management
* Commercial manned guarding
  * Abby Road
  * Fleet Street
* Mobile partrolling / intervention after alarm
* Other risks

(*Note*: "Other risks" are by definition risks that are present, that means the only 2 states can be "risk present" and "risk present, but at least one measure".)

7) Percentage per module and total percentage
At the top of the screen, close to the heading that contains the title of the tool, the overall percentage should be shown.
For each module, the percentage for that particular module should be shown.

Meaning of that percentage: This number should show the percentage of identified, postponed and not answered risks of the total number of risks of the module-location. This means that as the user eliminates risks from the organisation, the percentage should be coming closer to zero, which would mean that there are no risks present.

The colour in which the numbers are displayed will depend on the percentage. If there is a 100% of risks that are present, postponed or not answered, the number should be completely red. The colour should turn lighter as the number decreases until becoming green when the number reaches to zero. This way, it should only be green in case none of the risks of the module are present on the organisation.

The colour in which the numbers are displayed will depend on the value. A proposal for the colour code of the percentage is described below:

* Green (0%): There are no risks present in the module. 
* Light green (1% - 24%): There are a few risks in the module. 
* Orange (25% - 44%): There are some risks in the module.
* Light red (45% - 64%): The number of risks in the module is high. 
* Dark red (65% - 100%): There is a very high number of risks in the module.

**Comment by cornae** [comment]
This ticket was a pleasure to read. Very clear.

One question: The colours of the overall state, couldn't that just be completely gradual? So 98 shades between pure red and pure green?

**Comment by pysailor** [comment]
thanks ;-) 
Interesting idea about the colours. I think it makes sense. That would also distinguish the overall colour from one of the 5 discrete colours of the status bars.
And anyway, the message to the user is to get their modules as green as possible. With a gradient, every little step already has an effect.

**Comment by cornae** [comment]
It feels a bit counter intuitive to me to let 0% mean that all is okay and 100% that nothing is ok. I understand it comes form the risk thinking, but I think in a normal mind 100% and green go better together the 0% and green and 100% would mean "I'm now 100% fine". I sense a usability issue otherwise, but I could be wrong…

**Comment by pysailor** [comment]
Pretty good feedback so far! Switching the meaning to make 100% equal "I'm fine" was appreciated.

One request so far: can we please also show the number of unanwered risks in the status bar?

![status-bar-missing-number](https://cloud.githubusercontent.com/assets/642660/8987532/d54728d4-36e1-11e5-8ad9-50a4f88619b1.jpeg)

**Comment by pysailor** [comment]
I'll close this, since the status page is working really well. For change reqs that come in I'll created new tickets.
