### ISSUE TITLE
Guest user warning bar hides text in sessions modal

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#58]
The `#warning-bar` has an absolute position. During a guest session, when the users opens the sessions dropdown, the upper part is overshadowed by the the warning bar:
![screen shot 2015-07-10 at 11 03 21](https://cloud.githubusercontent.com/assets/642660/8615534/bd9ccee4-26f3-11e5-8526-715a2af63824.png)

If I disable `position: absolute` in the inspector, the text is shown:
![screen shot 2015-07-10 at 11 04 09](https://cloud.githubusercontent.com/assets/642660/8615546/d5f2a7de-26f3-11e5-8243-41f38dd6e84f.png)

This problem only occurs in `.tooltip-container`. Can you please add a rule to fix this?

**Comment by cornae** [comment]
The bar is only designed for the content area. I wouldn’t like to see it in the tooltips. What can we do?

**Comment by pysailor** [comment]
Could it be as simple as

    .tooltip-container #warning-bar {
      display: none;
    }
? Since the tooltip uses the same template as the general sessions overview, it's not easily possible to tell from the backend that in one case it's used in the content area, in the other inside a tooltip. Therefore I would opt for a CSS-based solution.

**Comment by cornae** [comment]
Ok.
