### ISSUE TITLE
Screen registration + terms and conditions

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#6]
https://client.oiratest.syslab.com/eu/@@register

The client has expressed the wish to combine registration and accepting the terms and conditions into a single screen. (Nice to have, not relevant for 1st version of proto)

![screen shot 2015-03-19 at 07 59 09](https://cloud.githubusercontent.com/assets/642660/6725728/f04f0ad0-ce0d-11e4-9515-2f4f9ce53975.png)
![screen shot 2015-03-19 at 07 59 44](https://cloud.githubusercontent.com/assets/642660/6725729/f428a2a6-ce0d-11e4-831d-7eed8ee93199.png)

**Comment by cornae** [comment]
One of the reasons it was not combined is the possible feedback that you user name already exists or that the 2 passwords don't correspond. You would each time have to scroll through the terms again. Of course if a simpel tick box that you've read them with a link to a page with the term suffices it's only one extra click. Still a click though… The most user friendly way is the Google way, where the label of the buttons states that by continuing you agree with the terms and conditions. Google's lawyers have agreed on that one, do OSH's?
