### ISSUE TITLE
Evaluation: Show problem description if risk is present

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#63]
Request by client: When a risk that needs to be evaluated (either via calculation or direct evaluation) is answered with "No", then the field-set for the evaluation should also show the risk's problem description, aka "negative statement".

The following screen-shot shows a _semantic_ explanation of the requirement - it should **not** be taken as design requirement :-) . Perhaps you want to mark the problem description in a completely different way (with quotes, with an icon, ...)?
![evaluation_problem_description](https://cloud.githubusercontent.com/assets/642660/8672212/83acff74-2a2c-11e5-86fb-2231f26e0a3a.jpeg)

**Comment by cornae** [comment]
How about this?

![image](https://cloud.githubusercontent.com/assets/738601/8944654/23f57820-3582-11e5-8eed-de58c9b87475.png)

I would love to work with your idea of a warning icon in front of it, but I find it difficult to style  in a way that it looks good for both 1 line and 2 line content.

**Comment by pysailor** [comment]
Cool, I think it's great the way you propose. Sold :-)
