### ISSUE TITLE
Improve "Pre-fill" tooltip menu

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#64]
On the Action plan, the tooltip-menu for pre-filling measures with common solutions has 2 issues:

1) The font size is quite small, compared to the surrounding text, making it somewhat difficult to read
2) The "Add" button is particularly small. Besides, since the whole line is clickable, it is not strictly needed. Do you think it makes sense to replace it with a symbol such as a plus sign?

<img width="1094" alt="screen shot 2015-07-14 at 14 11 46" src="https://cloud.githubusercontent.com/assets/642660/8673053/cddfc30e-2a33-11e5-8113-5da30302713a.png">

**Comment by cornae** [comment]
Question: the font-size of content on tooltips is everywhere the same size and made slightly smaller than standard content. Would you like to change that throughout the application? Or is just the text on the button too small? The other text is quite ok legible for me also on non-retina.

**Comment by cornae** [comment]
It now looks like this: 

![image](https://cloud.githubusercontent.com/assets/738601/8943610/d58279aa-357b-11e5-92da-b46bd1f603c7.png)

I cannot predict if using an icon instead of the safe design solution 'Add' will compromise usability, but it's probably fine.

**Comment by pysailor** [comment]
:+1: I like it. As for your question regarding text size: Seems perfectly readable to me too. I think the issue was really about the font size on the button
