### ISSUE TITLE
Improve styling "Legal refernces" on Identification

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#66]
In case there's a single image present on a risk, and the description text is short (or cut by truncation after a few lines), the heading "Legal and policy references" can also float to the right of the image (or at least partially), which looks ugly.

In proto, you can see this in /tool/private-security-eu/2014-01-27-exposure-to-noise-is-prevented-or-controlled.html (see a7aa179)

The `<h3>` probably needs a clear:left and some vertical spacing at the top.

<img width="1790" alt="screen shot 2015-07-17 at 17 19 19" src="https://cloud.githubusercontent.com/assets/642660/8750502/03d63350-2ca8-11e5-9473-d2fffd616c10.png">

**Comment by cornae** [comment]
I wish it were as simple as that. I had to invent a much more creative construct. I hope it doesn't have too many negative side effects in other places.

**Comment by pysailor** [comment]
Thanks! But the sub-heading "Legal and policy references" can still float to the right of an image, while it should always be displayed below the image. To be seen e.g. on
/tool/private-security-eu/2014-01-27-exposure-to-noise-is-prevented-or-controlled.html

<img width="1818" alt="screen shot 2015-07-28 at 14 50 14" src="https://cloud.githubusercontent.com/assets/642660/8931663/341dd23c-3538-11e5-9b56-1fb6a0f18609.png">

**Comment by cornae** [comment]
They do so because that's the intention of the design. If I position it always underneath I could indeed have save myself an hour and use a clear: left. But it's a 'more' pattern, which typically extends the text right where it ends, not leaving an ugly big white hole in the layout when there is more image than text. With what reason should it go underneath then?

**Comment by pysailor** [comment]
Legal & policy refs is a completely new part of the page, independent of the description (which can be expanded by the "more" pattern).
For the client, the perception is that this sub-heading, pushed to the right, followed by text that isn't, is more ugly than a potential white hole.

**Comment by cornae** [comment]
I agree. But this fix was still necessary for the more/less pattern that Floated over the image, which was the biggest bug in this page.

**Comment by cornae** [comment]
If it's usually only a bulleted list with hyperlinks, perhaps it would be nice experiment to make a well of it.

![image](https://cloud.githubusercontent.com/assets/738601/8942786/add2e808-3577-11e5-85f3-d915d110e64e.png)
