### ISSUE TITLE
Status page: replace circles with percentage with a smiley

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#72]
5 different types, from very sad / bad to super happy.

**Comment by cornae** [comment]
Smiley at the top still needs to be styled.

**Comment by pysailor** [comment]
@cornae Looks like the fix for values between 0 and 10 does not work, see f7cb0d9
Shall we use a leading zero? Would be no problem.

**Comment by pysailor** [comment]
Yeah, leading zero it is, trivial in python. All fine

**Comment by cornae** [comment]
It’s really strange it didn’t work. The css looks fine.

**Comment by cornae** [comment]
I understand now. It was a specificity issue. I can still fix it if you want :)

**Comment by pysailor** [comment]
Cornelis G. A. Kolbach wrote on 11/08/15 19:16:
> I understand now. It was a specificity issue. I can still fix it if
> you want :)
>
Yes, the more fuzzy 5 for 50 was found before the exact match for 5.
Feel free to fix for completeness' sake, but it's working well with the
leading zero.
