### ISSUE TITLE
Stand-alone HTML page for creating a report

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#75]
As discussed, we would need a stand-alone HTML page, i.e. outside the context of the OIRA app, to display a report about planned measures.

"The report will display information about the measures planned in the Action Plan phase of the risk assessment. It will display in a table with risks and measures in the rows and months in the columns, by module-location, the measures that are planned to start in the current month and the following two. Additionally, it will also display the priority of the risk that the measure is managing. All the elements that have to be shown in the report are detailed below"

![screen shot 2015-08-05 at 17 27 26](https://cloud.githubusercontent.com/assets/642660/9089854/994b6a24-3b97-11e5-9019-bd7a93983d2b.png)

1.	**Name of the module**: On the top of the page the report will show the name of the module and the location that is being reported.

2.	**Legend**: Under the name of the module-location, the report will display the legend of the icons that will be used in the table. The legend will be the one that is detailed in the picture above:
a.	Red dot: High priority risks.
b.	Orange dot: Medium priority risks.
c.	Green dot: Low priority risks.

3.	**Name of the risk**: In the rows of the table, the report will display the description of the risk. The description that is shown should be the negative statement of the risk. The colour in which the text is displayed will depend on the priority of the risk, being red for high priority risks, orange for medium and green for low. 

   The risks will be displayed starting with the ones of high priority on the top, followed by those of medium and with the low priority risks at the bottom.

4.	**Description of the measure**: Below the description of the risk, the rows will also display the description of the measure. This description will be the one entered by the user in the field ‘Description – general approach (to eliminate or reduce the risk)’ of the Action Plan phase of the risk assessment.

5.	**Months**: The month in which the report is generated and the upcoming two will be displayed in the columns of the tables of the report.

6.	**Intersection**: Each cell of the table will display a dot (as commented earlier, the colour will depend on the priority of the risk) if the risk has a measure that is planned to start in the month indicated by the column. Therefore, there will only be one dot for each row, because if one risk has more than one measure they will be displayed in different rows.

7.	**Catchline**: In the footer of each page of the Overview of measures report a catchline will be included. The text for the catchline will have to be decided by the OiRA team

**Comment by cornae** [comment]
Just a consideration: Dots in different colours instead of different symbols make the report less usable when printed on black & white printers. I know of large enterprises that still print stuff on black & white laser printers. The client might want to consider different unicode symbols that also take on these colours. Also good for the colour blind. 

Instead of using symbols and since the risks look grouped in the above design specification, the risks could also be grouped in the table using multiple tbody elements, each with a TR containing a TH that indicate the priority level. This would take the eventual need for using symbols away. I know what is above is the design requirement, but I see some flaws in the design that we might want to warn the client about. Unless I'm overlooking something…

Another consideration: Would the yellow that is specified here actually print with a high enough contrast on a black and white printer and even on some colour printers?

**Comment by pysailor** [comment]
All good considerations. Please follow on them! I see no reason why symbols instead of mere coloured dots can't be used.

**Comment by cornae** [comment]
Well it’s so awkward to rely fully on colour for print media, that I trust they must have a very good reason for it…

What about the grouping? Is it a pure coincidence that the risks are grouped by priority level and therefor not fully ordered in the same order as in the tool in the design specification, or was that just copy & paste laziness?

**Comment by pysailor** [comment]
Cornelis G. A. Kolbach wrote on 08/08/15 20:55:
> Well it’s so awkward to rely fully on colour for print media, that I
> trust they must have a very good reason for it…
Well, we both know where those requirements come from, so we can both
heartily doubt that a lot of reason went into this. My impression is
that to them it just looked nice on a screen, with little thought for
print...
>
> What about the grouping? Is it a pure coincidence that the risks are
> grouped by priority level and therefor not fully ordered in the same
> order as in the tool in the design specification, or was that just
> copy & paste laziness?
That, at least, is deliberate, see 3:
" The risks will be displayed starting with the ones of high priority on
the top, followed by those of medium and with the low priority risks at
the bottom."
>
> > Op 8 aug. 2015, om 20:53 heeft Wolfgang Thomas
> <notifications@github.com> het volgende geschreven:
> >
> > All good considerations. Please follow on them! I see no reason why
> symbols instead of mere coloured dots can't be used.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/euphorie/osha.oira/issues/75#issuecomment-129034483>.
>


-- 
Dipl.-Inf. Wolfgang Thomas

SYSLAB.COM GmbH, Landwehrstrasse 60-62, 80336 Munich, Germany
http://www.syslab.com
Amtsgericht Muenchen, HRB 135057
Steuernummer 143/184/50154, Ust.-ID: DE212842815 A

**Comment by cornae** [comment]
Alright. As I'm working on it, I was also thinking about using red and green for low and high prio. In the entire application we use these colours to indicate the state of the risk. Is the risk present, or not makes it green or red. But all the way at the end it suddenly means something else. Wouldn't you be afraid that this could be confusing?

**Comment by pysailor** [comment]
Yes I pointed this same fact out to them as well (we're defining the meaning of red and green.)
This is the answer I got:
"I agree that maybe the dual meaning of the colour could be misleading. Let's wait for a proposal from Cornelis."
I would interpret that as carte blanche...

**Comment by cornae** [comment]
It states:

> On the top of the page the report will show the name of the module and the location that is being reported.

I assume a report may contain multiple modules. Does the above line then mean that each module has to start a new page? If so, then I'll introduce a hard page break for each module in the CSS.

**Comment by pysailor** [comment]
Cornelis G. A. Kolbach wrote on 09/08/15 20:55:
>
> It states:
>
>     On the top of the page the report will show the name of the module
>     and the location that is being reported.
>
> I assume a report may contain multiple modules.
>
Yes, like the Status overview.
>
> Does the above line then mean that each module has to start a new
> page? If so, then I'll introduce a hard page break for each module in
> the CSS.
>
I think that makes a lot of sense.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/euphorie/osha.oira/issues/75#issuecomment-129225604>.
>


-- 
Dipl.-Inf. Wolfgang Thomas

SYSLAB.COM GmbH, Landwehrstrasse 60-62, 80336 Munich, Germany
http://www.syslab.com
Amtsgericht Muenchen, HRB 135057
Steuernummer 143/184/50154, Ust.-ID: DE212842815 A

**Comment by pysailor** [comment]
Thanks!
