### ISSUE TITLE
Screen "sessions" for specific tool

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#76]
Hi,
it seems we have overlooked a specific screen for the new OiRA UI, the one that a user sees if they access the OiRA app via the URL for a specific OiRA tool. In this case, we only want to list existing sessions for that specific tool (if any are present), and we don't need to offer a choice (drop-down) for starting a new session. The user does not need to pick a tool, but only needs to enter a name for the session of the tool in question.

In old OiRA, this screen looks like this (can be seen e.g. by going to https://client.oiraproject.eu/eu/eu-private-security/private-security-eu/)
<img width="816" alt="screen shot 2015-08-06 at 16 56 13" src="https://cloud.githubusercontent.com/assets/642660/9114938/bca06572-3c5c-11e5-8753-89c9d89f5ebf.png">

**Comment by pysailor** [comment]
@cornae I made a proposal in 9c51f06, can you please check if it's OK?
(That screen is not reachable by direct link in the proto, just enter /index-specific-tool.html directly.)

**Comment by cornae** [comment]
Looks good to me. Made a small markup adjustment.
