### ISSUE TITLE
Screen Preparation

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#8]
https://client.oiratest.syslab.com/eu/eu-private-security/private-security-eu/start
(you need to be logged in)

The page contains rich text entered by the creators of the OiRA tool. It can contain one logo.

![screen shot 2015-03-19 at 10 53 43](https://cloud.githubusercontent.com/assets/642660/6727966/5e3e7b1c-ce26-11e4-86ba-41ea29549c68.png)
![screen shot 2015-03-19 at 10 53 47](https://cloud.githubusercontent.com/assets/642660/6727969/610f8d36-ce26-11e4-9964-b9f768e09fe4.png)

**Comment by cornae** [comment]
@pysaylor, None of my e-mail/password combos work anymore and the demo version doesn't send password hints to my e-mail. Do you have working credentials form me?
