### ISSUE TITLE
Modal in mobile view opens with wrong dimensions

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#86]
On the prototype
http://proto.oira.syslab.com/
if I tap Login in a mobile device (here iPhone 6 from iOS simulator), the modal is too wide and tall to fit the screen:
<img width="487" alt="screen shot 2015-09-16 at 09 18 52" src="https://cloud.githubusercontent.com/assets/642660/9898661/6ad4768a-5c54-11e5-90d3-c058ab82fe87.png">

However, if I then tap into one of the text-lines, then the width of the modal gets reset to correct dimensions:
<img width="487" alt="screen shot 2015-09-16 at 09 19 07" src="https://cloud.githubusercontent.com/assets/642660/9898673/8da547ac-5c54-11e5-8c49-6082164f7c7e.png">
(note how the buttons on the bottom are still cut).

If I then close the modal, and tap Login again, it appears in correct dimensions:
<img width="487" alt="screen shot 2015-09-16 at 09 19 31" src="https://cloud.githubusercontent.com/assets/642660/9898734/f6d9fba0-5c54-11e5-832d-03a61014965c.png">

This can be repeated reliably, i.e. reload page, tap Login -> modal distorted. Close modal, open again -> modal fine.

**Comment by pysailor** [comment]
Hi @cornae - I heard that you might have a CSS solution for re-sizing modals. Could that be an option here?

**Comment by cornae** [comment]
Maybe, although this could be different. Have to research.
