### ISSUE TITLE
Functional links in action plan distorted in mobile

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#88]
If use "add another measure" on http://proto.oira.syslab.com/action-plan.html in mobile, you will see the link "delete this measure", together with "Pre-fill", appears half-way under the label "Measure 1"

<img width="487" alt="screen shot 2015-09-16 at 09 54 26" src="https://cloud.githubusercontent.com/assets/642660/9899323/590b569e-5c59-11e5-8aef-abb0e6379424.png">!

**Comment by pysailor** [comment]
@cornae Additional hint: originally, the link text was just "Remove", and that fir into 1 line. But even if we move back to that, the combination of "Pre-fill" and "Remove" might be too wide in some languages to fit next to the label "Measure X"

**Comment by cornae** [comment]
Solved it like this on small screen:

![simulator screen shot 24 sep 2015 23 26 12](https://cloud.githubusercontent.com/assets/738601/10087395/f09b95d0-6313-11e5-9edf-9b7ea228631a.png)

**Comment by pysailor** [comment]
I love it!

**Comment by cornae** [comment]
If you’re happy then I’m happy :)
