### ISSUE TITLE
Report box taller than screen in mobile

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#90]
On the page for downloading a report, the box for the individual reports gets taller than the screen (e.g. on iPhone 6)
http://proto.oira.syslab.com/report-download.html
<img width="487" alt="screen shot 2015-09-21 at 09 51 51" src="https://cloud.githubusercontent.com/assets/642660/9987268/a4cbb074-6046-11e5-84e1-53f9714ce3a3.png">

**Comment by cornae** [comment]
Solved it like this:

![simulator screen shot 25 sep 2015 00 26 53](https://cloud.githubusercontent.com/assets/738601/10088603/3851fc40-631c-11e5-9fca-39de44f1838e.png)

Also made the font size of the button smaller on mobile so that in 3 out of 4 cases the full text fits on the button.
