### ISSUE TITLE
Action plan: last image not displayed in mobile

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#91]
On the action plan http://proto.oira.syslab.com/action-plan.html when viewed with a mobile device,
the final image is not displayed. Instead, we see the background.
Happens in proto with the 4 images, but also in dev both with 4 images (3 shown) and 3 images (2 shown).

Screenshot from iPhone 6 simulator:
<img width="487" alt="screen shot 2015-09-21 at 12 21 58" src="https://cloud.githubusercontent.com/assets/642660/9989815/2f973a92-605c-11e5-8d19-2c530fb4af45.png">

**Comment by cornae** [comment]
This was by far the most interesting ticket so far as I didn't understand what was going on at a glance :).

**Comment by pysailor** [comment]
Glad I was able to provide you with a challenge :-)
And thanks for the fix!
