### ISSUE TITLE
In guest session, warning bar overlays content in mobile

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#94]
Very likely a direct result of the client requesting less space...

Nevertheless, could you please add a custom rule for mobile?

<img width="487" alt="screen shot 2015-09-25 at 18 38 00" src="https://cloud.githubusercontent.com/assets/642660/10106423/de4661f2-63b4-11e5-92c7-c9291d42c88d.png">

**Comment by cornae** [comment]
![simulator screen shot 26 sep 2015 20 31 26](https://cloud.githubusercontent.com/assets/738601/10119127/9905a3c6-648d-11e5-906c-a5949afa98d0.png)

**Comment by pysailor** [comment]
:+1:
