### ISSUE TITLE
IE11: Hamburger icon in smallest resolution distorted

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#95]
<img width="430" alt="screen shot 2015-09-25 at 18 35 26" src="https://cloud.githubusercontent.com/assets/642660/10106465/231d3738-63b5-11e5-8059-7d1a0123d9a4.png">

**Comment by cornae** [comment]
I could of course investigate into this ticket,  but do we actually expect desktop IE users to use the application with this viewport size?

**Comment by pysailor** [comment]
True, not very likely a real-world problem, let's leave it.
