### ISSUE TITLE
Splash message

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#97]
Hi,

the client would like to show a splash-message to users who log in to the Oira app, to tell them "Hey, look, it's all new and shiny, but don't worry, your old data is still there... etc"

And if a user clicks away the message, it should not be shown to them next time.

Sounds familiar? :-) I was thinking about whiteside, where you built a similar solution based on pat-collapsible with local storage.
I'll update index-logged-in.html with the markup. Could you please take a look and if possible in the OiRA context, style the collapsible like in whiteside?

**Comment by pysailor** [comment]
We need to cover the following:
It must be possible to force the splash message to appear even if the user has previously clicked it away. Reason: the site admin might change the text. In the whiteside, a id attribute on the pat-collapsible was used. That way, by using a UID, we are able to make the message appear again, even if the user has closed it before, by hanging the UID.

**Comment by cornae** [comment]
I've added the wild card (not tested yet, I'm in transit) but maybe you can see if it works as expected.

**Comment by pysailor** [comment]
Works just fine, thanks for the quick action!
