### ISSUE TITLE
Buttons for report downloads need to accomodate a lot of text

### ISSUE THREAD

**Issue by pysailor** [euphorie/osha.oira#99]
E.g. in Latvian:
<img width="1536" alt="screen shot 2015-10-10 at 16 06 35" src="https://cloud.githubusercontent.com/assets/642660/10411512/0c629f28-6f69-11e5-8c27-e5d5579adab5.png">

Can you find an alternative solution, e.g. more than one line?

**Comment by cornae** [comment]
The right solution would be to have not such descriptive content on a button but more only the keyword. Design cannot fix where content is wrong.

**Comment by pysailor** [comment]
Do we have an alternative to the "right solution" that does not require a rewrite?

**Comment by pysailor** [comment]
@cornae In other words: we have the texts that we have, and we will not got thru yet another round of communicating textual changes to all 15 partners for the languages. We need a solution that can work with those long texts. It would be acceptable to separate the descriptive text from the button label, and use "Download" as the label for all 4 buttons.

**Comment by pysailor** [comment]
continued in euphorie/oira.prototype#3
